name: automerge-all

on:
  workflow_run:
    workflows:
      - publish
    types:
      - completed
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - salesforcecli/plugin-apex
          - salesforcecli/plugin-auth
          - salesforcecli/plugin-community
          - salesforcecli/plugin-custom-metadata
          - salesforcecli/plugin-data
          - salesforcecli/plugin-dev
          - salesforcecli/plugin-env
          - salesforcecli/plugin-deploy-retrieve
          - salesforcecli/plugin-info
          - salesforcecli/plugin-limits
          - salesforcecli/plugin-marketplace
          - salesforcecli/plugin-org
          - salesforcecli/plugin-packaging
          #   - salesforcecli/plugin-release-management
          - salesforcecli/plugin-schema
          - salesforcecli/plugin-settings
          - salesforcecli/plugin-signups
          - salesforcecli/plugin-source
          - salesforcecli/plugin-sobject
          - salesforcecli/plugin-telemetry
          - salesforcecli/plugin-templates
          - salesforcecli/plugin-trust
          - salesforcecli/plugin-user
          - salesforcecli/sf-plugins-core
    steps:
      - name:
        run: gh workflow run automerge.yml --repo ${{ matrix.repo}}
        env:
          GH_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
